import type { ItineraryTemplateDescriptor } from "@/modules/itinerary/shared/itinerary-types";

export const ITINERARY_TEMPLATES: ItineraryTemplateDescriptor[] = [
  {
    key: "classic-brochure",
    title: "Classic Brochure",
    description:
      "A polished quotation-style itinerary with structured day pages, commercial summaries, and travel notes.",
    badge: "Document-led",
    supportedOutputs: ["DOCUMENT", "BOTH"],
    documentTheme: "Classic Journal",
    webTheme: "Editorial Landing",
    pageComposition: {
      document: [
        { family: "COVER", layoutVariant: "EDITORIAL_COVER" },
        { family: "TRIP_SUMMARY", layoutVariant: "FACT_GRID" },
        { family: "ROUTE_OVERVIEW", layoutVariant: "ROUTE_STORY" },
        { family: "HIGHLIGHTS", layoutVariant: "FEATURE_GRID" },
        { family: "DAY_DETAIL", layoutVariant: "TIMELINE_SPREAD" },
        { family: "ACCOMMODATION_SUMMARY", layoutVariant: "MATRIX_TABLE" },
        { family: "TRANSPORT_SUMMARY", layoutVariant: "MATRIX_TABLE" },
        { family: "PRICING_SUMMARY", layoutVariant: "COMMERCIAL_SUMMARY" },
        { family: "POLICY_NOTES", layoutVariant: "POLICY_COLUMNS" },
      ],
      web: [
        { family: "HERO", layoutVariant: "IMMERSIVE_HERO" },
        { family: "QUICK_FACTS", layoutVariant: "FACT_RIBBON" },
        { family: "ROUTE", layoutVariant: "ROUTE_SCROLLER" },
        { family: "TIMELINE", layoutVariant: "TIMELINE_CARDS" },
        { family: "STAYS", layoutVariant: "STAY_COLLECTION" },
        { family: "GALLERY", layoutVariant: "MEDIA_STORY_GRID" },
        { family: "PRICING", layoutVariant: "COMMERCIAL_PANEL" },
        { family: "TRAVEL_NOTES", layoutVariant: "TRAVEL_NOTES_STACK" },
        { family: "SUPPORT_FOOTER", layoutVariant: "SUPPORT_STRIP" },
      ],
    },
    documentFamilies: [
      "COVER",
      "TRIP_SUMMARY",
      "ROUTE_OVERVIEW",
      "HIGHLIGHTS",
      "DAY_DETAIL",
      "ACCOMMODATION_SUMMARY",
      "TRANSPORT_SUMMARY",
      "PRICING_SUMMARY",
      "POLICY_NOTES",
    ],
    webFamilies: [
      "HERO",
      "QUICK_FACTS",
      "ROUTE",
      "TIMELINE",
      "STAYS",
      "GALLERY",
      "PRICING",
      "TRAVEL_NOTES",
      "SUPPORT_FOOTER",
    ],
  },
  {
    key: "signature-story",
    title: "Signature Story",
    description:
      "A premium narrative itinerary that leans on destination mood, story-led highlights, and hospitality-driven presentation.",
    badge: "Balanced",
    supportedOutputs: ["DOCUMENT", "WEB", "BOTH"],
    documentTheme: "Signature Narrative",
    webTheme: "Story Microsite",
    pageComposition: {
      document: [
        { family: "COVER", layoutVariant: "EDITORIAL_COVER" },
        { family: "TRIP_SUMMARY", layoutVariant: "FACT_GRID" },
        { family: "HIGHLIGHTS", layoutVariant: "FEATURE_GRID" },
        { family: "DAY_DETAIL", layoutVariant: "TIMELINE_SPREAD" },
        { family: "ACCOMMODATION_SUMMARY", layoutVariant: "MATRIX_TABLE" },
        { family: "PRICING_SUMMARY", layoutVariant: "COMMERCIAL_SUMMARY" },
        { family: "POLICY_NOTES", layoutVariant: "POLICY_COLUMNS" },
      ],
      web: [
        { family: "HERO", layoutVariant: "IMMERSIVE_HERO" },
        { family: "QUICK_FACTS", layoutVariant: "FACT_RIBBON" },
        { family: "TIMELINE", layoutVariant: "TIMELINE_CARDS" },
        { family: "STAYS", layoutVariant: "STAY_COLLECTION" },
        { family: "GALLERY", layoutVariant: "MEDIA_STORY_GRID" },
        { family: "PRICING", layoutVariant: "COMMERCIAL_PANEL" },
        { family: "TRAVEL_NOTES", layoutVariant: "TRAVEL_NOTES_STACK" },
        { family: "SUPPORT_FOOTER", layoutVariant: "SUPPORT_STRIP" },
      ],
    },
    documentFamilies: [
      "COVER",
      "TRIP_SUMMARY",
      "HIGHLIGHTS",
      "DAY_DETAIL",
      "ACCOMMODATION_SUMMARY",
      "PRICING_SUMMARY",
      "POLICY_NOTES",
    ],
    webFamilies: [
      "HERO",
      "QUICK_FACTS",
      "TIMELINE",
      "STAYS",
      "GALLERY",
      "PRICING",
      "TRAVEL_NOTES",
      "SUPPORT_FOOTER",
    ],
  },
  {
    key: "web-landing",
    title: "Web Landing",
    description:
      "A share-ready microsite foundation with a strong hero, route storytelling, and immersive timeline sections.",
    badge: "Web-first",
    supportedOutputs: ["WEB", "BOTH"],
    documentTheme: "Compact Summary",
    webTheme: "Destination Story",
    pageComposition: {
      document: [
        { family: "COVER", layoutVariant: "EDITORIAL_COVER" },
        { family: "TRIP_SUMMARY", layoutVariant: "FACT_GRID" },
        { family: "DAY_DETAIL", layoutVariant: "TIMELINE_SPREAD" },
        { family: "PRICING_SUMMARY", layoutVariant: "COMMERCIAL_SUMMARY" },
      ],
      web: [
        { family: "HERO", layoutVariant: "IMMERSIVE_HERO" },
        { family: "QUICK_FACTS", layoutVariant: "FACT_RIBBON" },
        { family: "ROUTE", layoutVariant: "ROUTE_SCROLLER" },
        { family: "TIMELINE", layoutVariant: "TIMELINE_CARDS" },
        { family: "STAYS", layoutVariant: "STAY_COLLECTION" },
        { family: "GALLERY", layoutVariant: "MEDIA_STORY_GRID" },
        { family: "PRICING", layoutVariant: "COMMERCIAL_PANEL" },
        { family: "TRAVEL_NOTES", layoutVariant: "TRAVEL_NOTES_STACK" },
        { family: "SUPPORT_FOOTER", layoutVariant: "SUPPORT_STRIP" },
      ],
    },
    documentFamilies: [
      "COVER",
      "TRIP_SUMMARY",
      "DAY_DETAIL",
      "PRICING_SUMMARY",
    ],
    webFamilies: [
      "HERO",
      "QUICK_FACTS",
      "ROUTE",
      "TIMELINE",
      "STAYS",
      "GALLERY",
      "PRICING",
      "TRAVEL_NOTES",
      "SUPPORT_FOOTER",
    ],
  },
];

export function getItineraryTemplate(templateKey: string) {
  return ITINERARY_TEMPLATES.find((template) => template.key === templateKey) ?? null;
}
