import type { Metadata } from "next";
import { AppConfirmProvider } from "@/components/app-confirm-provider";
import { ClientLogBootstrap } from "@/components/logging/client-log-bootstrap";
import { Geist, Geist_Mono } from "next/font/google";
import { AppToaster } from "@/components/app-toaster";
import "leaflet/dist/leaflet.css";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppConfirmProvider>
          <ClientLogBootstrap />
          {children}
          <AppToaster />
        </AppConfirmProvider>
      </body>
    </html>
  );
}
