import type { Metadata } from "next";
import { AppConfirmProvider } from "@/components/app-confirm-provider";
import { AppQueryProvider } from "@/components/app-query-provider";
import { ClientLogBootstrap } from "@/components/logging/client-log-bootstrap";
import { AppToaster } from "@/components/app-toaster";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className="antialiased">
        <AppQueryProvider>
          <AppConfirmProvider>
            <ClientLogBootstrap />
            {children}
            <AppToaster />
          </AppConfirmProvider>
        </AppQueryProvider>
      </body>
    </html>
  );
}
