import type { ImportEntityConfig } from "./master-batch-import-dialog";

export const locationImportConfig: ImportEntityConfig = {
  key: "locations",
  title: "Locations",
  description:
    "Download the sample sheet, fill location records in Excel, save as CSV, then upload and validate before saving.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "name", label: "Name", required: true, type: "text" },
    { key: "country", label: "Country", type: "text" },
    { key: "region", label: "Region", type: "text" },
    { key: "address", label: "Address", type: "text" },
    { key: "notes", label: "Notes", type: "text" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "CMB",
    name: "Colombo City",
    country: "Sri Lanka",
    region: "Western",
    address: "Colombo 03",
    notes: "Main city pickup point",
    isActive: "true",
  },
};

export const hotelImportConfig: ImportEntityConfig = {
  key: "hotels",
  title: "Hotels",
  description:
    "Upload accommodation hotels in bulk. Star rating must be 1-5 and duplicate hotel codes are blocked.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "name", label: "Name", required: true, type: "text" },
    { key: "description", label: "Description", type: "text" },
    { key: "address", label: "Address", required: true, type: "text" },
    { key: "city", label: "City", required: true, type: "text" },
    { key: "country", label: "Country", required: true, type: "text" },
    { key: "starRating", label: "Star Rating", required: true, type: "number" },
    { key: "contactEmail", label: "Contact Email", type: "text" },
    { key: "contactPhone", label: "Contact Phone", type: "text" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "HTL-CMB-001",
    name: "City View Hotel",
    description: "Business and leisure hotel",
    address: "No 12, Marine Drive",
    city: "Colombo",
    country: "Sri Lanka",
    starRating: "4",
    contactEmail: "reservations@cityview.com",
    contactPhone: "+94-11-1234567",
    isActive: "true",
  },
};

export const activityImportConfig: ImportEntityConfig = {
  key: "activities",
  title: "Activities",
  description:
    "Activity upload validates activity type and location code against master data before save.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    {
      key: "type",
      label: "Type",
      required: true,
      type: "dropdown",
      options: [
        { value: "ACTIVITY", label: "ACTIVITY" },
        { value: "SUPPLEMENT", label: "SUPPLEMENT" },
        { value: "MISCELLANEOUS", label: "MISCELLANEOUS" },
        { value: "OTHER", label: "OTHER" },
      ],
    },
    { key: "locationCode", label: "Location Code", required: true, type: "dropdown", options: [] },
    { key: "locationRole", label: "Location Role", type: "text" },
    { key: "name", label: "Name", required: true, type: "text" },
    { key: "shortDescription", label: "Short Description", type: "text" },
    { key: "description", label: "Description", type: "text" },
    { key: "durationMin", label: "Duration (Min)", type: "number" },
    { key: "minPax", label: "Min Pax", type: "number" },
    { key: "maxPax", label: "Max Pax", type: "number" },
    { key: "minAge", label: "Min Age", type: "number" },
    { key: "maxAge", label: "Max Age", type: "number" },
    { key: "notes", label: "Notes", type: "text" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "ACT-KDY-001",
    type: "ACTIVITY",
    locationCode: "KDY",
    locationRole: "ACTIVITY_LOCATION",
    name: "Temple & City Tour",
    shortDescription: "Half-day city experience",
    description: "Includes key cultural attractions in Kandy.",
    durationMin: "240",
    minPax: "1",
    maxPax: "20",
    minAge: "0",
    maxAge: "70",
    notes: "",
    isActive: "true",
  },
};

export const activityRateImportConfig: ImportEntityConfig = {
  key: "activity-rates",
  title: "Activity Rates",
  description:
    "Upload activity rate lines in bulk. Supports FIXED, PER_PAX, TIERED_PAX, PER_HOUR, and PER_UNIT models.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "activityCode", label: "Activity Code", required: true, type: "dropdown", options: [] },
    { key: "label", label: "Label", type: "text" },
    { key: "currency", label: "Currency", type: "text" },
    {
      key: "pricingModel",
      label: "Pricing Model",
      type: "dropdown",
      options: [
        { value: "FIXED", label: "FIXED" },
        { value: "PER_PAX", label: "PER_PAX" },
        { value: "TIERED_PAX", label: "TIERED_PAX" },
        { value: "PER_HOUR", label: "PER_HOUR" },
        { value: "PER_UNIT", label: "PER_UNIT" },
      ],
    },
    { key: "fixedRate", label: "Fixed Rate", type: "number" },
    { key: "perPaxRate", label: "Per Pax Rate", type: "number" },
    { key: "perHourRate", label: "Per Hour Rate", type: "number" },
    { key: "perUnitRate", label: "Per Unit Rate", type: "number" },
    { key: "paxTiersJson", label: "Pax Tiers JSON", type: "text" },
    { key: "minCharge", label: "Min Charge", type: "number" },
    { key: "effectiveFrom", label: "Effective From (ISO)", type: "text" },
    { key: "effectiveTo", label: "Effective To (ISO)", type: "text" },
    { key: "notes", label: "Notes", type: "text" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "AR-RAFT-001",
    activityCode: "ACT-KDY-001",
    label: "Standard Per Pax",
    currency: "LKR",
    pricingModel: "PER_PAX",
    fixedRate: "",
    perPaxRate: "4500",
    perHourRate: "",
    perUnitRate: "",
    paxTiersJson: "",
    minCharge: "0",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    effectiveTo: "",
    notes: "",
    isActive: "true",
  },
};

export const guideImportConfig: ImportEntityConfig = {
  key: "guides",
  title: "Guides",
  description:
    "Guide upload validates guide type, gender, rating range, and base currency code from master currency.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    {
      key: "guideType",
      label: "Guide Type",
      required: true,
      type: "dropdown",
      options: [
        { value: "INDIVIDUAL", label: "INDIVIDUAL" },
        { value: "COMPANY", label: "COMPANY" },
        { value: "INTERNAL", label: "INTERNAL" },
      ],
    },
    { key: "fullName", label: "Full Name", required: true, type: "text" },
    { key: "displayName", label: "Display Name", type: "text" },
    {
      key: "gender",
      label: "Gender",
      type: "dropdown",
      options: [
        { value: "MALE", label: "MALE" },
        { value: "FEMALE", label: "FEMALE" },
        { value: "OTHER", label: "OTHER" },
        { value: "PREFER_NOT_TO_SAY", label: "PREFER_NOT_TO_SAY" },
      ],
    },
    { key: "phone", label: "Phone", type: "text" },
    { key: "email", label: "Email", type: "text" },
    { key: "address", label: "Address", type: "text" },
    { key: "countryCode", label: "Country", type: "text" },
    { key: "city", label: "City", type: "text" },
    { key: "bio", label: "Bio", type: "text" },
    { key: "yearsExperience", label: "Years Experience", type: "number" },
    { key: "rating", label: "Rating (0-5)", type: "number" },
    { key: "baseCurrencyCode", label: "Base Currency Code", type: "dropdown", options: [] },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "G-0001",
    guideType: "INDIVIDUAL",
    fullName: "Nuwan Perera",
    displayName: "Nuwan",
    gender: "MALE",
    phone: "0717565838",
    email: "nuwan@example.com",
    address: "Matara",
    countryCode: "LK",
    city: "Matara",
    bio: "English speaking guide",
    yearsExperience: "8",
    rating: "4.5",
    baseCurrencyCode: "LKR",
    isActive: "true",
  },
};

export const transportVehicleCategoryImportConfig: ImportEntityConfig = {
  key: "vehicle-categories",
  title: "Transport Vehicle Categories",
  description: "Bulk upload vehicle category master records.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "name", label: "Name", required: true, type: "text" },
    { key: "description", label: "Description", type: "text" },
    { key: "sortOrder", label: "Sort Order", type: "number" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "SUV",
    name: "SUV",
    description: "Sports Utility Vehicle",
    sortOrder: "1",
    isActive: "true",
  },
};

export const transportVehicleTypeImportConfig: ImportEntityConfig = {
  key: "vehicle-types",
  title: "Transport Vehicle Types",
  description: "Bulk upload vehicle type records with category code mapping.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "categoryCode", label: "Category Code", required: true, type: "dropdown", options: [] },
    { key: "name", label: "Name", required: true, type: "text" },
    { key: "paxCapacity", label: "Pax Capacity", required: true, type: "number" },
    { key: "baggageCapacity", label: "Baggage Capacity", type: "number" },
    { key: "featuresJson", label: "Features JSON", type: "text" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "VAN-01",
    categoryCode: "VAN",
    name: "Standard Van",
    paxCapacity: "8",
    baggageCapacity: "6",
    featuresJson: "[\"AC\",\"WIFI\"]",
    isActive: "true",
  },
};

export const transportLocationRateImportConfig: ImportEntityConfig = {
  key: "location-rates",
  title: "Transport Location Rates",
  description: "Bulk upload point-to-point rates using location and vehicle code mappings.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "fromLocationCode", label: "From Location Code", required: true, type: "dropdown", options: [] },
    { key: "toLocationCode", label: "To Location Code", required: true, type: "dropdown", options: [] },
    { key: "vehicleCategoryCode", label: "Vehicle Category Code", type: "dropdown", options: [] },
    { key: "vehicleTypeCode", label: "Vehicle Type Code", type: "dropdown", options: [] },
    { key: "distanceKm", label: "Distance KM", type: "number" },
    { key: "durationMin", label: "Duration Min", type: "number" },
    { key: "currency", label: "Currency", type: "text" },
    {
      key: "pricingModel",
      label: "Pricing Model",
      type: "dropdown",
      options: [
        { value: "FIXED", label: "FIXED" },
        { value: "PER_KM", label: "PER_KM" },
        { value: "SLAB", label: "SLAB" },
      ],
    },
    { key: "fixedRate", label: "Fixed Rate", type: "number" },
    { key: "perKmRate", label: "Per KM Rate", type: "number" },
    { key: "slabsJson", label: "Slabs JSON", type: "text" },
    { key: "minCharge", label: "Min Charge", type: "number" },
    { key: "nightSurcharge", label: "Night Surcharge", type: "number" },
    { key: "effectiveFrom", label: "Effective From (ISO)", type: "text" },
    { key: "effectiveTo", label: "Effective To (ISO)", type: "text" },
    { key: "notes", label: "Notes", type: "text" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "LR-CMB-KDY-01",
    fromLocationCode: "CMB",
    toLocationCode: "KDY",
    vehicleCategoryCode: "SEDAN",
    vehicleTypeCode: "",
    distanceKm: "115",
    durationMin: "180",
    currency: "LKR",
    pricingModel: "FIXED",
    fixedRate: "18000",
    perKmRate: "",
    slabsJson: "",
    minCharge: "0",
    nightSurcharge: "0",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    effectiveTo: "",
    notes: "",
    isActive: "true",
  },
};

export const transportLocationExpenseImportConfig: ImportEntityConfig = {
  key: "location-expenses",
  title: "Transport Location Expenses",
  description: "Bulk upload location expense lines.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "locationCode", label: "Location Code", required: true, type: "dropdown", options: [] },
    { key: "name", label: "Name", required: true, type: "text" },
    {
      key: "expenseType",
      label: "Expense Type",
      required: true,
      type: "dropdown",
      options: [
        { value: "FIXED", label: "FIXED" },
        { value: "PER_DAY", label: "PER_DAY" },
        { value: "PER_HOUR", label: "PER_HOUR" },
        { value: "PER_PAX", label: "PER_PAX" },
        { value: "PER_VEHICLE", label: "PER_VEHICLE" },
      ],
    },
    { key: "amount", label: "Amount", required: true, type: "number" },
    { key: "currency", label: "Currency", type: "text" },
    { key: "vehicleCategoryCode", label: "Vehicle Category Code", type: "dropdown", options: [] },
    { key: "vehicleTypeCode", label: "Vehicle Type Code", type: "dropdown", options: [] },
    { key: "effectiveFrom", label: "Effective From (ISO)", type: "text" },
    { key: "effectiveTo", label: "Effective To (ISO)", type: "text" },
    { key: "notes", label: "Notes", type: "text" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "LE-CMB-01",
    locationCode: "CMB",
    name: "Parking Fee",
    expenseType: "FIXED",
    amount: "1500",
    currency: "LKR",
    vehicleCategoryCode: "",
    vehicleTypeCode: "",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    effectiveTo: "",
    notes: "",
    isActive: "true",
  },
};

export const transportPaxVehicleRateImportConfig: ImportEntityConfig = {
  key: "pax-vehicle-rates",
  title: "Transport Pax Vehicle Rates",
  description: "Bulk upload transport pax-based pricing lines.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "fromLocationCode", label: "From Location Code", required: true, type: "dropdown", options: [] },
    { key: "toLocationCode", label: "To Location Code", required: true, type: "dropdown", options: [] },
    { key: "vehicleCategoryCode", label: "Vehicle Category Code", type: "dropdown", options: [] },
    { key: "vehicleTypeCode", label: "Vehicle Type Code", type: "dropdown", options: [] },
    { key: "currency", label: "Currency", type: "text" },
    {
      key: "pricingModel",
      label: "Pricing Model",
      type: "dropdown",
      options: [
        { value: "PER_PAX", label: "PER_PAX" },
        { value: "TIERED", label: "TIERED" },
      ],
    },
    { key: "perPaxRate", label: "Per Pax Rate", type: "number" },
    { key: "tiersJson", label: "Tiers JSON", type: "text" },
    { key: "minCharge", label: "Min Charge", type: "number" },
    { key: "effectiveFrom", label: "Effective From (ISO)", type: "text" },
    { key: "effectiveTo", label: "Effective To (ISO)", type: "text" },
    { key: "notes", label: "Notes", type: "text" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "PR-CMB-KDY-01",
    fromLocationCode: "CMB",
    toLocationCode: "KDY",
    vehicleCategoryCode: "VAN",
    vehicleTypeCode: "",
    currency: "LKR",
    pricingModel: "PER_PAX",
    perPaxRate: "2500",
    tiersJson: "",
    minCharge: "0",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    effectiveTo: "",
    notes: "",
    isActive: "true",
  },
};

export const transportBaggageRateImportConfig: ImportEntityConfig = {
  key: "baggage-rates",
  title: "Transport Baggage Rates",
  description: "Bulk upload baggage transport pricing lines.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "fromLocationCode", label: "From Location Code", required: true, type: "dropdown", options: [] },
    { key: "toLocationCode", label: "To Location Code", required: true, type: "dropdown", options: [] },
    { key: "vehicleCategoryCode", label: "Vehicle Category Code", type: "dropdown", options: [] },
    { key: "vehicleTypeCode", label: "Vehicle Type Code", type: "dropdown", options: [] },
    { key: "currency", label: "Currency", type: "text" },
    {
      key: "unit",
      label: "Unit",
      type: "dropdown",
      options: [
        { value: "BAG", label: "BAG" },
        { value: "KG", label: "KG" },
      ],
    },
    {
      key: "pricingModel",
      label: "Pricing Model",
      type: "dropdown",
      options: [
        { value: "PER_UNIT", label: "PER_UNIT" },
        { value: "TIERED", label: "TIERED" },
        { value: "FIXED", label: "FIXED" },
      ],
    },
    { key: "perUnitRate", label: "Per Unit Rate", type: "number" },
    { key: "fixedRate", label: "Fixed Rate", type: "number" },
    { key: "tiersJson", label: "Tiers JSON", type: "text" },
    { key: "minCharge", label: "Min Charge", type: "number" },
    { key: "effectiveFrom", label: "Effective From (ISO)", type: "text" },
    { key: "effectiveTo", label: "Effective To (ISO)", type: "text" },
    { key: "notes", label: "Notes", type: "text" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "BR-CMB-KDY-01",
    fromLocationCode: "CMB",
    toLocationCode: "KDY",
    vehicleCategoryCode: "",
    vehicleTypeCode: "",
    currency: "LKR",
    unit: "BAG",
    pricingModel: "PER_UNIT",
    perUnitRate: "500",
    fixedRate: "",
    tiersJson: "",
    minCharge: "0",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    effectiveTo: "",
    notes: "",
    isActive: "true",
  },
};
