import type { ImportEntityConfig } from "./master-batch-import-dialog";
import {
  HOTEL_BOARD_BASES,
  HOTEL_CONTRACT_STATUSES,
  HOTEL_CONTRACT_TYPES,
  HOTEL_PENALTY_BASES,
  HOTEL_PENALTY_TYPES,
  HOTEL_RATE_PRICING_MODELS,
  HOTEL_RATE_TYPES,
  HOTEL_TAX_MODES,
  HOTEL_TRIP_MARKET_SCOPES,
} from "@/modules/accommodation/shared/accommodation-contracting-types";

export const locationImportConfig: ImportEntityConfig = {
  key: "locations",
  title: "Locations",
  description:
    "Download the sample sheet, fill location records in Excel, save as CSV, then upload and validate before saving.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "name", label: "Name", required: true, type: "text" },
    { key: "country", label: "Country", type: "text" },
    { key: "region", label: "Region", type: "text" },
    { key: "address", label: "Address", type: "text" },
    { key: "notes", label: "Notes", type: "text" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "CMB",
    name: "Colombo City",
    country: "Sri Lanka",
    region: "Western",
    address: "Colombo 03",
    notes: "Main city pickup point",
    isActive: "true",
  },
};

export const hotelImportConfig: ImportEntityConfig = {
  key: "hotels",
  title: "Hotels",
  description:
    "Upload accommodation hotels in bulk using a system location code from master locations. If address is left blank, the selected master location address will be used.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "name", label: "Name", required: true, type: "text" },
    { key: "description", label: "Description", type: "text" },
    { key: "address", label: "Address", type: "text" },
    { key: "locationCode", label: "Location Code", required: true, type: "dropdown", options: [] },
    { key: "starRating", label: "Star Rating", required: true, type: "number" },
    { key: "contactEmail", label: "Contact Email", type: "text" },
    { key: "contactPhone", label: "Contact Phone", type: "text" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "HTL-CMB-001",
    name: "City View Hotel",
    description: "Business and leisure hotel",
    address: "No 12, Marine Drive",
    locationCode: "CMB",
    starRating: "4",
    contactEmail: "reservations@cityview.com",
    contactPhone: "+94-11-1234567",
    isActive: "true",
  },
};

export const hotelRoomTypeImportConfig: ImportEntityConfig = {
  key: "hotel-room-types",
  title: "Hotel Room Types",
  description:
    "Upload hotel room types in bulk for the selected hotel. Duplicate room type codes are blocked.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "name", label: "Name", required: true, type: "text" },
    { key: "description", label: "Description", type: "text" },
    { key: "bedType", label: "Bed Type", required: true, type: "text" },
    { key: "maxOccupancy", label: "Max Occupancy", required: true, type: "number" },
    { key: "size", label: "Size", type: "text" },
    { key: "amenitiesCsv", label: "Amenities CSV", type: "text" },
    { key: "totalRooms", label: "Total Rooms", required: true, type: "number" },
    { key: "availableRooms", label: "Available Rooms", type: "number" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "DLX-KING",
    name: "Deluxe King",
    description: "Large room with city view",
    bedType: "King Bed",
    maxOccupancy: "2",
    size: "42 sqm",
    amenitiesCsv: "WiFi, TV, Mini Bar",
    totalRooms: "24",
    availableRooms: "24",
    isActive: "true",
  },
};

export const hotelContractImportConfig: ImportEntityConfig = {
  key: "hotel-contracts",
  title: "Hotel Contracts",
  description:
    "Upload top-level hotel contracts in bulk for the selected hotel. This import covers contract headers only.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "name", label: "Name", type: "text" },
    { key: "supplierCode", label: "Supplier Code", type: "dropdown", options: [] },
    { key: "contractRef", label: "Contract Ref", type: "text" },
    {
      key: "contractType",
      label: "Contract Type",
      required: true,
      type: "dropdown",
      options: HOTEL_CONTRACT_TYPES.map((value) => ({ value, label: value })),
    },
    { key: "currencyCode", label: "Currency", required: true, type: "text" },
    { key: "validFrom", label: "Valid From", required: true, type: "text" },
    { key: "validTo", label: "Valid To", required: true, type: "text" },
    { key: "bookingFrom", label: "Booking From", type: "text" },
    { key: "bookingTo", label: "Booking To", type: "text" },
    { key: "releaseDaysDefault", label: "Release Days", type: "number" },
    {
      key: "marketScope",
      label: "Market Scope",
      type: "dropdown",
      options: HOTEL_TRIP_MARKET_SCOPES.map((value) => ({ value, label: value })),
    },
    { key: "guestNationalityScope", label: "Guest Nationality Scope", type: "text" },
    { key: "remarks", label: "Remarks", type: "text" },
    {
      key: "status",
      label: "Status",
      type: "dropdown",
      options: HOTEL_CONTRACT_STATUSES.map((value) => ({ value, label: value })),
    },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "FIT-2026-SUMMER",
    name: "Summer FIT Contract",
    supplierCode: "SUP-001",
    contractRef: "CN-2026-SUMMER",
    contractType: "FIT",
    currencyCode: "USD",
    validFrom: "2026-05-01",
    validTo: "2026-10-31",
    bookingFrom: "2026-01-01",
    bookingTo: "2026-10-15",
    releaseDaysDefault: "14",
    marketScope: "ALL_MARKETS",
    guestNationalityScope: "",
    remarks: "",
    status: "ACTIVE",
    isActive: "true",
  },
};

export const hotelRatePlanImportConfig: ImportEntityConfig = {
  key: "hotel-rate-plans",
  title: "Hotel Rate Plans",
  description:
    "Upload rate plans in bulk for the selected contract. Cancellation policy code is optional.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "name", label: "Name", required: true, type: "text" },
    { key: "description", label: "Description", type: "text" },
    {
      key: "rateType",
      label: "Rate Type",
      required: true,
      type: "dropdown",
      options: HOTEL_RATE_TYPES.map((value) => ({ value, label: value })),
    },
    {
      key: "boardBasis",
      label: "Board Basis",
      required: true,
      type: "dropdown",
      options: HOTEL_BOARD_BASES.map((value) => ({ value, label: value })),
    },
    {
      key: "pricingModel",
      label: "Pricing Model",
      type: "dropdown",
      options: HOTEL_RATE_PRICING_MODELS.map((value) => ({ value, label: value })),
    },
    { key: "cancellationPolicyCode", label: "Cancellation Policy Code", type: "dropdown", options: [] },
    { key: "validFrom", label: "Valid From", required: true, type: "text" },
    { key: "validTo", label: "Valid To", required: true, type: "text" },
    { key: "bookingFrom", label: "Booking From", type: "text" },
    { key: "bookingTo", label: "Booking To", type: "text" },
    { key: "releaseDaysOverride", label: "Release Days Override", type: "number" },
    { key: "marketCode", label: "Market Code", type: "text" },
    { key: "guestNationalityScope", label: "Guest Nationality Scope", type: "text" },
    { key: "isRefundable", label: "Refundable", type: "boolean" },
    { key: "isCommissionable", label: "Commissionable", type: "boolean" },
    { key: "isPackageOnly", label: "Package Only", type: "boolean" },
    { key: "priority", label: "Priority", type: "number" },
    {
      key: "status",
      label: "Status",
      type: "dropdown",
      options: HOTEL_CONTRACT_STATUSES.map((value) => ({ value, label: value })),
    },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "BB-FIT",
    name: "Bed & Breakfast FIT",
    description: "Primary FIT contracted plan",
    rateType: "CONTRACTED_BUY",
    boardBasis: "BB",
    pricingModel: "PER_ROOM_PER_NIGHT",
    cancellationPolicyCode: "",
    validFrom: "2026-05-01",
    validTo: "2026-10-31",
    bookingFrom: "2026-01-01",
    bookingTo: "2026-10-15",
    releaseDaysOverride: "7",
    marketCode: "FIT",
    guestNationalityScope: "",
    isRefundable: "true",
    isCommissionable: "false",
    isPackageOnly: "false",
    priority: "1",
    status: "ACTIVE",
    isActive: "true",
  },
};

export const hotelRoomRateImportConfig: ImportEntityConfig = {
  key: "hotel-room-rates",
  title: "Hotel Room Rates",
  description:
    "Upload occupancy room rates in bulk for the selected rate plan. Room type code must exist in the selected hotel.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "roomTypeCode", label: "Room Type Code", required: true, type: "dropdown", options: [] },
    { key: "validFrom", label: "Valid From", required: true, type: "text" },
    { key: "validTo", label: "Valid To", required: true, type: "text" },
    { key: "bookingFrom", label: "Booking From", type: "text" },
    { key: "bookingTo", label: "Booking To", type: "text" },
    { key: "marketCode", label: "Market Code", type: "text" },
    { key: "guestNationalityScope", label: "Guest Nationality Scope", type: "text" },
    { key: "baseOccupancyAdults", label: "Base Occupancy Adults", required: true, type: "number" },
    { key: "baseOccupancyChildren", label: "Base Occupancy Children", type: "number" },
    { key: "maxAdults", label: "Max Adults", required: true, type: "number" },
    { key: "maxChildren", label: "Max Children", type: "number" },
    { key: "maxOccupancy", label: "Max Occupancy", type: "number" },
    { key: "singleUseRate", label: "Single Use Rate", type: "number" },
    { key: "doubleRate", label: "Double Rate", type: "number" },
    { key: "tripleRate", label: "Triple Rate", type: "number" },
    { key: "quadRate", label: "Quad Rate", type: "number" },
    { key: "extraAdultRate", label: "Extra Adult Rate", type: "number" },
    { key: "childWithBedRate", label: "Child With Bed Rate", type: "number" },
    { key: "childNoBedRate", label: "Child No Bed Rate", type: "number" },
    { key: "infantRate", label: "Infant Rate", type: "number" },
    { key: "singleSupplementRate", label: "Single Supplement Rate", type: "number" },
    { key: "currencyCode", label: "Currency", required: true, type: "text" },
    {
      key: "taxMode",
      label: "Tax Mode",
      type: "dropdown",
      options: HOTEL_TAX_MODES.map((value) => ({ value, label: value })),
    },
    { key: "remarks", label: "Remarks", type: "text" },
    {
      key: "status",
      label: "Status",
      type: "dropdown",
      options: HOTEL_CONTRACT_STATUSES.map((value) => ({ value, label: value })),
    },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "DLX-BB-2026",
    roomTypeCode: "DLX-KING",
    validFrom: "2026-05-01",
    validTo: "2026-10-31",
    bookingFrom: "2026-01-01",
    bookingTo: "2026-10-15",
    marketCode: "FIT",
    guestNationalityScope: "",
    baseOccupancyAdults: "2",
    baseOccupancyChildren: "0",
    maxAdults: "2",
    maxChildren: "1",
    maxOccupancy: "3",
    singleUseRate: "110",
    doubleRate: "145",
    tripleRate: "",
    quadRate: "",
    extraAdultRate: "35",
    childWithBedRate: "25",
    childNoBedRate: "15",
    infantRate: "0",
    singleSupplementRate: "20",
    currencyCode: "USD",
    taxMode: "EXCLUSIVE",
    remarks: "",
    status: "ACTIVE",
    isActive: "true",
  },
};

export const hotelCancellationPolicyImportConfig: ImportEntityConfig = {
  key: "hotel-cancellation-policies",
  title: "Hotel Cancellation Policies",
  description:
    "Upload cancellation policy headers in bulk for the selected hotel.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "name", label: "Name", required: true, type: "text" },
    { key: "description", label: "Description", type: "text" },
    { key: "noShowPolicy", label: "No-show Policy", type: "text" },
    { key: "afterCheckInPolicy", label: "After Check-in Policy", type: "text" },
    { key: "isDefault", label: "Is Default", type: "boolean" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "CAN-FLEX",
    name: "Flexible Policy",
    description: "Standard flexible cancellation terms",
    noShowPolicy: "Full first night charge",
    afterCheckInPolicy: "Non-refundable after check-in",
    isDefault: "false",
    isActive: "true",
  },
};

export const hotelCancellationPolicyRuleImportConfig: ImportEntityConfig = {
  key: "hotel-cancellation-policy-rules",
  title: "Hotel Cancellation Policy Rules",
  description:
    "Upload penalty windows in bulk for the selected cancellation policy.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "fromDaysBefore", label: "From Days Before", type: "number" },
    { key: "toDaysBefore", label: "To Days Before", type: "number" },
    {
      key: "penaltyType",
      label: "Penalty Type",
      required: true,
      type: "dropdown",
      options: HOTEL_PENALTY_TYPES.map((value) => ({ value, label: value })),
    },
    { key: "penaltyValue", label: "Penalty Value", required: true, type: "number" },
    {
      key: "basis",
      label: "Basis",
      type: "dropdown",
      options: HOTEL_PENALTY_BASES.map((value) => ({ value, label: value })),
    },
    { key: "appliesOnNoShow", label: "Applies On No-show", type: "boolean" },
    { key: "appliesAfterCheckIn", label: "Applies After Check-in", type: "boolean" },
  ],
  sampleRow: {
    code: "CAN-30-15",
    fromDaysBefore: "30",
    toDaysBefore: "15",
    penaltyType: "PERCENT",
    penaltyValue: "50",
    basis: "TOTAL_STAY",
    appliesOnNoShow: "false",
    appliesAfterCheckIn: "false",
  },
};

export const hotelRateRestrictionImportConfig: ImportEntityConfig = {
  key: "hotel-rate-restrictions",
  title: "Hotel Rate Restrictions",
  description:
    "Upload restrictions in bulk for the selected rate plan. Room type code is optional.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "roomTypeCode", label: "Room Type Code", type: "dropdown", options: [] },
    { key: "stayFrom", label: "Stay From", required: true, type: "text" },
    { key: "stayTo", label: "Stay To", required: true, type: "text" },
    { key: "bookingFrom", label: "Booking From", type: "text" },
    { key: "bookingTo", label: "Booking To", type: "text" },
    { key: "minStay", label: "Min Stay", type: "number" },
    { key: "maxStay", label: "Max Stay", type: "number" },
    { key: "closedToArrival", label: "Closed To Arrival", type: "boolean" },
    { key: "closedToDeparture", label: "Closed To Departure", type: "boolean" },
    { key: "stopSell", label: "Stop Sell", type: "boolean" },
    { key: "releaseDays", label: "Release Days", type: "number" },
    { key: "notes", label: "Notes", type: "text" },
  ],
  sampleRow: {
    code: "CTA-JAN",
    roomTypeCode: "DLX-KING",
    stayFrom: "2026-12-20",
    stayTo: "2027-01-05",
    bookingFrom: "",
    bookingTo: "",
    minStay: "2",
    maxStay: "",
    closedToArrival: "true",
    closedToDeparture: "false",
    stopSell: "false",
    releaseDays: "7",
    notes: "Peak season arrival control",
  },
};

export const activityImportConfig: ImportEntityConfig = {
  key: "activities",
  title: "Activities",
  description:
    "Activity upload validates activity type and location code against master data before save.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    {
      key: "type",
      label: "Type",
      required: true,
      type: "dropdown",
      options: [
        { value: "ACTIVITY", label: "ACTIVITY" },
        { value: "SUPPLEMENT", label: "SUPPLEMENT" },
        { value: "MISCELLANEOUS", label: "MISCELLANEOUS" },
        { value: "OTHER", label: "OTHER" },
      ],
    },
    { key: "locationCode", label: "Location Code", required: true, type: "dropdown", options: [] },
    { key: "locationRole", label: "Location Role", type: "text" },
    { key: "name", label: "Name", required: true, type: "text" },
    { key: "shortDescription", label: "Short Description", type: "text" },
    { key: "description", label: "Description", type: "text" },
    { key: "durationMin", label: "Duration (Min)", type: "number" },
    { key: "minPax", label: "Min Pax", type: "number" },
    { key: "maxPax", label: "Max Pax", type: "number" },
    { key: "minAge", label: "Min Age", type: "number" },
    { key: "maxAge", label: "Max Age", type: "number" },
    { key: "notes", label: "Notes", type: "text" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "ACT-KDY-001",
    type: "ACTIVITY",
    locationCode: "KDY",
    locationRole: "ACTIVITY_LOCATION",
    name: "Temple & City Tour",
    shortDescription: "Half-day city experience",
    description: "Includes key cultural attractions in Kandy.",
    durationMin: "240",
    minPax: "1",
    maxPax: "20",
    minAge: "0",
    maxAge: "70",
    notes: "",
    isActive: "true",
  },
};

export const activityRateImportConfig: ImportEntityConfig = {
  key: "activity-rates",
  title: "Activity Rates",
  description:
    "Upload activity rate lines in bulk. Supports FIXED, PER_PAX, TIERED_PAX, PER_HOUR, and PER_UNIT models.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "activityCode", label: "Activity Code", required: true, type: "dropdown", options: [] },
    { key: "label", label: "Label", type: "text" },
    { key: "currency", label: "Currency", type: "text" },
    {
      key: "pricingModel",
      label: "Pricing Model",
      type: "dropdown",
      options: [
        { value: "FIXED", label: "FIXED" },
        { value: "PER_PAX", label: "PER_PAX" },
        { value: "TIERED_PAX", label: "TIERED_PAX" },
        { value: "PER_HOUR", label: "PER_HOUR" },
        { value: "PER_UNIT", label: "PER_UNIT" },
      ],
    },
    { key: "fixedRate", label: "Fixed Rate", type: "number" },
    { key: "perPaxRate", label: "Per Pax Rate", type: "number" },
    { key: "perHourRate", label: "Per Hour Rate", type: "number" },
    { key: "perUnitRate", label: "Per Unit Rate", type: "number" },
    { key: "paxTiersJson", label: "Pax Tiers JSON", type: "text" },
    { key: "minCharge", label: "Min Charge", type: "number" },
    { key: "effectiveFrom", label: "Effective From (ISO)", type: "text" },
    { key: "effectiveTo", label: "Effective To (ISO)", type: "text" },
    { key: "notes", label: "Notes", type: "text" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "AR-RAFT-001",
    activityCode: "ACT-KDY-001",
    label: "Standard Per Pax",
    currency: "LKR",
    pricingModel: "PER_PAX",
    fixedRate: "",
    perPaxRate: "4500",
    perHourRate: "",
    perUnitRate: "",
    paxTiersJson: "",
    minCharge: "0",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    effectiveTo: "",
    notes: "",
    isActive: "true",
  },
};

export const guideImportConfig: ImportEntityConfig = {
  key: "guides",
  title: "Guides",
  description:
    "Guide upload validates guide type, gender, rating range, and base currency code from master currency.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    {
      key: "guideType",
      label: "Guide Type",
      required: true,
      type: "dropdown",
      options: [
        { value: "INDIVIDUAL", label: "INDIVIDUAL" },
        { value: "COMPANY", label: "COMPANY" },
        { value: "INTERNAL", label: "INTERNAL" },
      ],
    },
    { key: "fullName", label: "Full Name", required: true, type: "text" },
    { key: "displayName", label: "Display Name", type: "text" },
    {
      key: "gender",
      label: "Gender",
      type: "dropdown",
      options: [
        { value: "MALE", label: "MALE" },
        { value: "FEMALE", label: "FEMALE" },
        { value: "OTHER", label: "OTHER" },
        { value: "PREFER_NOT_TO_SAY", label: "PREFER_NOT_TO_SAY" },
      ],
    },
    { key: "phone", label: "Phone", type: "text" },
    { key: "email", label: "Email", type: "text" },
    { key: "address", label: "Address", type: "text" },
    { key: "countryCode", label: "Country", type: "text" },
    { key: "city", label: "City", type: "text" },
    { key: "bio", label: "Bio", type: "text" },
    { key: "yearsExperience", label: "Years Experience", type: "number" },
    { key: "rating", label: "Rating (0-5)", type: "number" },
    { key: "baseCurrencyCode", label: "Base Currency Code", type: "dropdown", options: [] },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "G-0001",
    guideType: "INDIVIDUAL",
    fullName: "Nuwan Perera",
    displayName: "Nuwan",
    gender: "MALE",
    phone: "0717565838",
    email: "nuwan@example.com",
    address: "Matara",
    countryCode: "LK",
    city: "Matara",
    bio: "English speaking guide",
    yearsExperience: "8",
    rating: "4.5",
    baseCurrencyCode: "LKR",
    isActive: "true",
  },
};

export const transportVehicleCategoryImportConfig: ImportEntityConfig = {
  key: "vehicle-categories",
  title: "Transport Vehicle Categories",
  description: "Bulk upload vehicle category master records.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "name", label: "Name", required: true, type: "text" },
    { key: "description", label: "Description", type: "text" },
    { key: "sortOrder", label: "Sort Order", type: "number" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "SUV",
    name: "SUV",
    description: "Sports Utility Vehicle",
    sortOrder: "1",
    isActive: "true",
  },
};

export const transportVehicleTypeImportConfig: ImportEntityConfig = {
  key: "vehicle-types",
  title: "Transport Vehicle Types",
  description: "Bulk upload vehicle type records with category code mapping.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "categoryCode", label: "Category Code", required: true, type: "dropdown", options: [] },
    { key: "name", label: "Name", required: true, type: "text" },
    { key: "paxCapacity", label: "Pax Capacity", required: true, type: "number" },
    { key: "baggageCapacity", label: "Baggage Capacity", type: "number" },
    { key: "featuresJson", label: "Features JSON", type: "text" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "VAN-01",
    categoryCode: "VAN",
    name: "Standard Van",
    paxCapacity: "8",
    baggageCapacity: "6",
    featuresJson: "[\"AC\",\"WIFI\"]",
    isActive: "true",
  },
};

export const transportLocationRateImportConfig: ImportEntityConfig = {
  key: "location-rates",
  title: "Transport Location Rates",
  description: "Bulk upload point-to-point rates using location and vehicle code mappings.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "fromLocationCode", label: "From Location Code", required: true, type: "dropdown", options: [] },
    { key: "toLocationCode", label: "To Location Code", required: true, type: "dropdown", options: [] },
    { key: "vehicleCategoryCode", label: "Vehicle Category Code", type: "dropdown", options: [] },
    { key: "vehicleTypeCode", label: "Vehicle Type Code", type: "dropdown", options: [] },
    { key: "distanceKm", label: "Distance KM", type: "number" },
    { key: "durationMin", label: "Duration Min", type: "number" },
    { key: "currency", label: "Currency", type: "text" },
    {
      key: "pricingModel",
      label: "Pricing Model",
      type: "dropdown",
      options: [
        { value: "FIXED", label: "FIXED" },
        { value: "PER_KM", label: "PER_KM" },
        { value: "SLAB", label: "SLAB" },
      ],
    },
    { key: "fixedRate", label: "Fixed Rate", type: "number" },
    { key: "perKmRate", label: "Per KM Rate", type: "number" },
    { key: "slabsJson", label: "Slabs JSON", type: "text" },
    { key: "minCharge", label: "Min Charge", type: "number" },
    { key: "nightSurcharge", label: "Night Surcharge", type: "number" },
    { key: "effectiveFrom", label: "Effective From (ISO)", type: "text" },
    { key: "effectiveTo", label: "Effective To (ISO)", type: "text" },
    { key: "notes", label: "Notes", type: "text" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "LR-CMB-KDY-01",
    fromLocationCode: "CMB",
    toLocationCode: "KDY",
    vehicleCategoryCode: "SEDAN",
    vehicleTypeCode: "",
    distanceKm: "115",
    durationMin: "180",
    currency: "LKR",
    pricingModel: "FIXED",
    fixedRate: "18000",
    perKmRate: "",
    slabsJson: "",
    minCharge: "0",
    nightSurcharge: "0",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    effectiveTo: "",
    notes: "",
    isActive: "true",
  },
};

export const transportLocationExpenseImportConfig: ImportEntityConfig = {
  key: "location-expenses",
  title: "Transport Location Expenses",
  description: "Bulk upload location expense lines.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "locationCode", label: "Location Code", required: true, type: "dropdown", options: [] },
    { key: "name", label: "Name", required: true, type: "text" },
    {
      key: "expenseType",
      label: "Expense Type",
      required: true,
      type: "dropdown",
      options: [
        { value: "FIXED", label: "FIXED" },
        { value: "PER_DAY", label: "PER_DAY" },
        { value: "PER_HOUR", label: "PER_HOUR" },
        { value: "PER_PAX", label: "PER_PAX" },
        { value: "PER_VEHICLE", label: "PER_VEHICLE" },
      ],
    },
    { key: "amount", label: "Amount", required: true, type: "number" },
    { key: "currency", label: "Currency", type: "text" },
    { key: "vehicleCategoryCode", label: "Vehicle Category Code", type: "dropdown", options: [] },
    { key: "vehicleTypeCode", label: "Vehicle Type Code", type: "dropdown", options: [] },
    { key: "effectiveFrom", label: "Effective From (ISO)", type: "text" },
    { key: "effectiveTo", label: "Effective To (ISO)", type: "text" },
    { key: "notes", label: "Notes", type: "text" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "LE-CMB-01",
    locationCode: "CMB",
    name: "Parking Fee",
    expenseType: "FIXED",
    amount: "1500",
    currency: "LKR",
    vehicleCategoryCode: "",
    vehicleTypeCode: "",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    effectiveTo: "",
    notes: "",
    isActive: "true",
  },
};

export const transportPaxVehicleRateImportConfig: ImportEntityConfig = {
  key: "pax-vehicle-rates",
  title: "Transport Pax Vehicle Rates",
  description: "Bulk upload transport pax-based pricing lines.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "fromLocationCode", label: "From Location Code", required: true, type: "dropdown", options: [] },
    { key: "toLocationCode", label: "To Location Code", required: true, type: "dropdown", options: [] },
    { key: "vehicleCategoryCode", label: "Vehicle Category Code", type: "dropdown", options: [] },
    { key: "vehicleTypeCode", label: "Vehicle Type Code", type: "dropdown", options: [] },
    { key: "currency", label: "Currency", type: "text" },
    {
      key: "pricingModel",
      label: "Pricing Model",
      type: "dropdown",
      options: [
        { value: "PER_PAX", label: "PER_PAX" },
        { value: "TIERED", label: "TIERED" },
      ],
    },
    { key: "perPaxRate", label: "Per Pax Rate", type: "number" },
    { key: "tiersJson", label: "Tiers JSON", type: "text" },
    { key: "minCharge", label: "Min Charge", type: "number" },
    { key: "effectiveFrom", label: "Effective From (ISO)", type: "text" },
    { key: "effectiveTo", label: "Effective To (ISO)", type: "text" },
    { key: "notes", label: "Notes", type: "text" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "PR-CMB-KDY-01",
    fromLocationCode: "CMB",
    toLocationCode: "KDY",
    vehicleCategoryCode: "VAN",
    vehicleTypeCode: "",
    currency: "LKR",
    pricingModel: "PER_PAX",
    perPaxRate: "2500",
    tiersJson: "",
    minCharge: "0",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    effectiveTo: "",
    notes: "",
    isActive: "true",
  },
};

export const transportBaggageRateImportConfig: ImportEntityConfig = {
  key: "baggage-rates",
  title: "Transport Baggage Rates",
  description: "Bulk upload baggage transport pricing lines.",
  fields: [
    { key: "code", label: "Code", required: true, type: "text" },
    { key: "fromLocationCode", label: "From Location Code", required: true, type: "dropdown", options: [] },
    { key: "toLocationCode", label: "To Location Code", required: true, type: "dropdown", options: [] },
    { key: "vehicleCategoryCode", label: "Vehicle Category Code", type: "dropdown", options: [] },
    { key: "vehicleTypeCode", label: "Vehicle Type Code", type: "dropdown", options: [] },
    { key: "currency", label: "Currency", type: "text" },
    {
      key: "unit",
      label: "Unit",
      type: "dropdown",
      options: [
        { value: "BAG", label: "BAG" },
        { value: "KG", label: "KG" },
      ],
    },
    {
      key: "pricingModel",
      label: "Pricing Model",
      type: "dropdown",
      options: [
        { value: "PER_UNIT", label: "PER_UNIT" },
        { value: "TIERED", label: "TIERED" },
        { value: "FIXED", label: "FIXED" },
      ],
    },
    { key: "perUnitRate", label: "Per Unit Rate", type: "number" },
    { key: "fixedRate", label: "Fixed Rate", type: "number" },
    { key: "tiersJson", label: "Tiers JSON", type: "text" },
    { key: "minCharge", label: "Min Charge", type: "number" },
    { key: "effectiveFrom", label: "Effective From (ISO)", type: "text" },
    { key: "effectiveTo", label: "Effective To (ISO)", type: "text" },
    { key: "notes", label: "Notes", type: "text" },
    { key: "isActive", label: "Is Active", type: "boolean" },
  ],
  sampleRow: {
    code: "BR-CMB-KDY-01",
    fromLocationCode: "CMB",
    toLocationCode: "KDY",
    vehicleCategoryCode: "",
    vehicleTypeCode: "",
    currency: "LKR",
    unit: "BAG",
    pricingModel: "PER_UNIT",
    perUnitRate: "500",
    fixedRate: "",
    tiersJson: "",
    minCharge: "0",
    effectiveFrom: "2026-01-01T00:00:00.000Z",
    effectiveTo: "",
    notes: "",
    isActive: "true",
  },
};
